FROM python:3.10

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY requirements-test.txt .
RUN pip install -r requirements-test.txt

ARG USER=docker-build
ARG UID=1000
ARG GID=1000

RUN echo UID:GID = ${UID}:${GID}
RUN if [ ${GID} != 1000 ] && [ ${GID} != 0 ]; then groupadd --gid=${GID} ${USER}; exit 0; fi;
RUN if [ ${UID} != 1000 ] && [ ${UID} != 0 ]; then useradd --create-home -d /home/docker-build --no-log-init --uid=${UID} -g ${GID} ${USER}; fi;

USER ${UID}:${GID}

