name: Pyright

on:
  push:
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.393
